version: "3.3"

services: 
  postgres:
    image: postgres:14-alpine
    env_file: 
      - config.env
    volumes: 
      - db-data:/var/lib/postgresql/data
  api-adapter:
    build: https://github.com/truflation/api-adapter.git#develop
    restart: always
    env_file:
      - config.env
  tfi-marketplace-orders:
    build:
       context: ./modules/orders
    restart: always
    env_file:
      - config.env
  chainlink:
    build:
       context: ./chainnode
    env_file:
      - config.env
    command: node start -p /chainlink/.password -a /chainlink/.api
    restart: on-failure
    ports:
      - 6689:6688
    links:
      - postgres
    depends_on:
      - postgres
      - api-adapter
      - tfi-marketplace-orders
    volumes:
      - chainlink_data:/chainlink
  chainlink-link:
    build:
       context: ./chainnode
    env_file:
      - config.env.link
    command: node start -p /chainlink/.password -a /chainlink/.api
    restart: on-failure
    ports: 
      - 6690:6688
    links:
      - postgres
    depends_on: 
      - postgres
      - api-adapter
      - tfi-marketplace-orders
    volumes:
      - chainlink_link_data:/chainlink
  frontend:
     build:
       context: https://github.com/truflation/sample-frontend.git#develop
       args:
         inflationAddress: "0x79053120810FdDf61ceFB781fc898D1cf52A44a0"
         apiAddress: "0xF4A440F09B52dCFCe0303BD81f457761cB008Bb4"
     ports:
       - 9012:9011
     depends_on:
       - chainlink
volumes: 
  db-data:
  chainlink_data:
  chainlink_link_data:
