type = "directrequest"
schemaVersion = 1
name = ""
externalJobID = "5db955da-bd33-4024-8614-06858e1fbbe2"
maxTaskDuration = "0s"
contractAddress = "0x7C2e0E489493e487903941F399A0255C4c170C91"
minContractPaymentLinkJuels = "0"
observationSource = """
fetch [type="bridge" name="orders" requestData="$(jobRun)"]
submit_tx  [type="ethtx" to="0x7C2e0E489493e487903941F399A0255C4c170C91" data="$(fetch)"]

fetch -> submit_tx
"""
